# Generated by Django 2.1 on 2019-01-13 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duedate', models.DateField()),
                ('shareno', models.IntegerField()),
                ('current_status', models.CharField(max_length=30)),
                ('users_invested_id', models.IntegerField()),
                ('real_estates_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('sender', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=50)),
                ('body', models.TextField(blank=True)),
                ('unread', models.BooleanField(default=True)),
                ('time_sent', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
                ('body', models.TextField(blank=True)),
                ('unread', models.BooleanField(default=True)),
                ('time_notified', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_type', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('year', models.IntegerField()),
                ('site_mi', models.BooleanField()),
                ('area', models.IntegerField()),
                ('oda_no', models.IntegerField()),
                ('salon_no', models.IntegerField()),
                ('banyo_no', models.IntegerField()),
                ('heating', models.CharField(max_length=30)),
                ('owner_id', models.IntegerField()),
                ('campaign_id', models.IntegerField()),
            ],
        ),
    ]
