# Generated by Django 2.1 on 2019-01-28 17:05

from django.db import migrations, models
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from dash.models import Actor, User

# Define groups
g_owner = Group.objects.get_or_create(name='owner')[0]
g_staff = Group.objects.get_or_create(name='staff')[0]
g_client = Group.objects.get_or_create(name='client')[0]


class Migration(migrations.Migration):


    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
    ]
