# Generated by Django 2.1 on 2019-01-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20190126_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='imagedir',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m'),
        ),
    ]
