# Generated by Django 2.1 on 2019-01-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_remove_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
