# Generated by Django 2.1 on 2019-01-27 13:11

import dash.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20190127_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='imagedir',
            field=models.ImageField(upload_to='images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='videodir',
            field=models.FileField(upload_to='videos/%Y/%m', validators=[dash.validators.validate_video]),
        ),
    ]
