# Generated by Django 2.1 on 2019-01-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20190127_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='actor',
            name='video',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='actor',
            name='imagedir',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='actor',
            name='videodir',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
